#!/bin/bash
set -e

echo "=== Readylytics Dev Container Setup ==="

# 1. Generate local.properties if missing
if [ ! -f local.properties ]; then
    echo "Generating local.properties..."
    cat > local.properties <<EOF
# Generated by .devcontainer/post-create.sh
sdk.dir=${ANDROID_HOME}
cmake.dir=
ndk.dir=
EOF
    echo "✓ local.properties created"
fi

# 2. Verify gradle wrapper exists
if [ ! -x gradlew ]; then
    echo "ERROR: gradle wrapper not found at ./gradlew" >&2
    exit 1
fi
echo "✓ Gradle wrapper found"

# 3. Warm up Gradle cache (pre-download dependencies)
# This runs `./gradlew projects` to trigger dependency resolution and caching
# Runs in background without daemon to avoid leftover processes
echo "Warming up Gradle cache (first run, ~2-3 min)..."
./gradlew projects --no-daemon -q 2>/dev/null || true
echo "✓ Gradle cache warmed"

# 4. Display helpful information
echo ""
echo "=== Readylytics Dev Container Ready ==="
echo ""
echo "Available build commands:"
echo "  ./gradlew ktlintFormat              # Format Kotlin code"
echo "  ./gradlew testDebugUnitTest         # Run unit tests"
echo "  ./gradlew assembleDebug             # Build debug APK"
echo "  ./gradlew lint lintRelease          # Android lint checks"
echo "  ./gradlew jacocoTestReport          # Generate coverage report"
echo "  ./gradlew jacocoCoverageVerification # Verify coverage gates"
echo ""
echo "Pre-commit verification:"
echo "  ./gradlew ktlintFormat && ./gradlew testDebugUnitTest && ./gradlew lintRelease"
echo ""
echo "AI Coding Tools:"
echo "  claude --version                # Anthropic Claude Code"
echo "  codex --version                 # OpenAI Codex CLI"
echo "  antigravity --version           # Google Antigravity CLI"
echo ""
echo "Authenticate coding tools:"
echo "  claude login                    # Interactive browser OAuth"
echo "  export ANTHROPIC_API_KEY='sk-ant-...' # Or use env var"
echo "  export OPENAI_API_KEY='sk-...'        # For OpenAI Codex"
echo "  export ANTIGRAVITY_API_KEY='...'      # For Google Antigravity"
echo ""
echo "Limitations (require external tools):"
echo "  ✗ Instrumented tests: Requires Android emulator (Android Studio or external)"
echo "  ✗ Health Connect APIs: Device/emulator only (mock data for unit tests)"
echo "  ✗ Real-time debugging: Requires Android Studio debugger attachment"
echo "  ✗ Release builds: Requires signing keys + Play Console access"
echo ""
echo "Next steps:"
echo "  1. Review .devcontainer/README.md for detailed setup instructions"
echo "  2. Set up AI tool authentication (claude login, etc.)"
echo "  3. Run ./gradlew assembleDebug to verify build works"
echo ""
