package app.readylytics.health.domain.model

import java.time.LocalDate

data class DailySummary(
    val date: LocalDate,
    val sleepScore: Float? = null,
    val loadScore: Float? = null,
    val readinessScore: Float? = null,
    val strainRatio: Float? = null,
    val nocturnalHrv: Int? = null,
    val sleepDurationMinutes: Int? = null,
    val deepSleepPercent: Float? = null,
    val remSleepPercent: Float? = null,
    val totalTrimp: Float? = null,
    val hrvBaseline: Int? = null,
    val restingHeartRate: Int? = null,
    val restingHrRatio: Float? = null,
    val paiScore: Float? = null,
    val totalPai: Float? = null,
    val stepCount: Int? = null,
    val zLnHrv: Float? = null,
    val zRhr: Float? = null,
    val recoveryFlags: Set<RecoveryFlag> = emptySet(),
    val hrvSigma: Float? = null,
    val readinessResult: ReadinessResult = ReadinessResult.EMPTY,
    val sRest: Float? = null,
    val isCalibrating: Boolean = false,
    val weightKg: Float? = null,
    val bodyFatPercent: Float? = null,
    val bloodPressureSystolic: Int? = null,
    val bloodPressureDiastolic: Int? = null,
    val avgSleepingSpo2: Float? = null,
    val hrvMuMssd: Float? = null,
    val hrvSigmaMssd: Float? = null,
    val rhrBpm: Float? = null,
    val rhrSigma: Float? = null,
    val baselineCalculatedAtDate: LocalDate? = null,
    val hrMax: Float? = null,
    val snapshotProfile: String? = null,
    val snapshotCalibrationPhase: String? = null,
    val hrvSigmaPrior: Float? = null,
    val paiScalingFactor: Float? = null,
    val baselineObservationCount: Int? = null,
    val trimpWorkoutOnly: Float? = null,
    val trimpEverydayHr: Float? = null,
    val paiWorkoutOnly: Float? = null,
    val paiEverydayHr: Float? = null,
    val totalPaiWorkoutOnly: Float? = null,
    val totalPaiEverydayHr: Float? = null,
    val atlWorkoutOnly: Float? = null,
    val atlEverydayHr: Float? = null,
    val ctlWorkoutOnly: Float? = null,
    val ctlEverydayHr: Float? = null,
    val strainRatioWorkoutOnly: Float? = null,
    val strainRatioEverydayHr: Float? = null,
    val loadScoreWorkoutOnly: Float? = null,
    val loadScoreEverydayHr: Float? = null,
    val readinessWorkoutOnly: Float? = null,
    val readinessEverydayHr: Float? = null,
    val everydayCoverageMinutes: Int? = null,
    val everydayLoadConfidence: String? = null,
)
